name: Projeto FOME CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Repositorio
      uses: actions/checkout@v2

    - name: Instalacao JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Rodar Maven
      run: mvn clean install

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy ambiente DEV AWS
      uses: appleboy/ssh-action@v0.5.2
      with:
        host: ${{ secrets.EC2_DEV_HOST }}
        username: ${{ secrets.EC2_DEV_USERNAME }}
        key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
        script: |
          cd /maven/home/bin/
          git pull origin main
          ./mvnw clean install
          mvn spring-boot:run

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy ambiente PROD AWS
      uses: appleboy/ssh-action@v0.5.2
      with:
        host: ${{ secrets.EC2_PROD_HOST }}
        username: ${{ secrets.EC2_PROD_USERNAME }}
        key: ${{ secrets.EC2_PROD_PRIVATE_KEY }}
        script: |
          cd /maven/home/bin/
          git pull origin main
          ./mvnw clean install
          mvn spring-boot:run

  cloudfront-invalidation:
    needs: deploy-prod
    runs-on: ubuntu-latest

    steps:
    - name: AWS CLI Setup
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'Sao Paulo'

    - name: CloudFront Invalidation
      run: |
        aws cloudfront create-invalidation --distribution-id 'ID DA DISTRIBUICAO' --paths '/*'
